{
 "title": "JVM Overview Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "pod_name",
    "label": "pod_name",
    "query": "label_values(kubernetes_pod_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "expr": "java_lang_Runtime_Uptime{kubernetes_pod_name=~\"$pod_name\"}"
    }
   ]
  },
  {
   "title": "Heap Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 7, "x": 8, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(jvm_memory_pool_bytes_used{kubernetes_pod_name=~\"$pod_name\", pool=~\"PS Eden Space|PS Old Gen|PS Survivor Space\"})*100/sum(jvm_memory_pool_bytes_max{kubernetes_pod_name=~\"$pod_name\", pool=~\"PS Eden Space|PS Old Gen|PS Survivor Space\"})"
    }
   ]
  },
  {
   "title": "Non Heap Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 9, "x": 15, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(jvm_memory_pool_bytes_used{kubernetes_pod_name=~\"$pod_name\", pool=~\"Metaspace|Code Cache|Compressed Class Space\"})*100/sum(jvm_memory_pool_bytes_max{kubernetes_pod_name=~\"$pod_name\", pool=~\"Metaspace|Code Cache|Compressed Class Space\"})"
    }
   ]
  },
  {
   "title": "JVM Memory Pools(Non-Heap)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_used{kubernetes_pod_name=~\"$pod_name\", pool=~\"Metaspace|Code Cache|Compressed Class Space\"}",
     "legendFormat": "{{pool}} [{$pod_name}]"
    }
   ]
  },
  {
   "title": "JVM Memory Pools(Heap)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 3 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_used{kubernetes_pod_name=~\"$pod_name\", pool=~\"PS Eden Space|PS Old Gen|PS Survivor Space\"}",
     "legendFormat": "{{pool}} [{$pod_name}]"
    }
   ]
  },
  {
   "title": "JVM Total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_bytes_used{kubernetes_pod_name=~\"$pod_name\"})",
     "legendFormat": "{{used}}"
    },
    {
     "expr": "sum(jvm_memory_bytes_committed{kubernetes_pod_name=~\"$pod_name\"})",
     "legendFormat": "{{committed}}"
    },
    {
     "expr": "sum(jvm_memory_bytes_max{kubernetes_pod_name=~\"$pod_name\"})",
     "legendFormat": "{{max}}"
    }
   ]
  },
  {
   "title": "JVM Native Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 11 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "java_nio_BufferPool_TotalCapacity{kubernetes_pod_name=~\"$pod_name\"}",
     "legendFormat": "{{name}}  [{$pod_name}]"
    }
   ]
  },
  {
   "title": "ThreadDeadlocked",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_deadlocked_monitor{kubernetes_pod_name=\"$pod_name\"}",
     "legendFormat": "threads_deadlocked_monitor[{$pod_name}]"
    },
    {
     "expr": "jvm_threads_deadlocked{kubernetes_pod_name=\"$pod_name\"}",
     "legendFormat": "threads_deadlocked[{$pod_name}]"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 7, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "java_lang_OperatingSystem_MaxFileDescriptorCount{kubernetes_pod_name=~\"$pod_name\"}",
     "legendFormat": "MaxFileDescriptorCount[{$pod_name}]"
    },
    {
     "expr": "java_lang_OperatingSystem_OpenFileDescriptorCount{kubernetes_pod_name=~\"$pod_name\"}",
     "legendFormat": "OpenFileDescriptorCount[{$pod_name}]"
    }
   ]
  },
  {
   "title": "GC count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_gc_collection_seconds_count{kubernetes_pod_name=~\"$pod_name\"}",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  {
   "title": "GC Collection Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(java_lang_GarbageCollector_CollectionCount{kubernetes_pod_name=~\"$pod_name\"}[5m])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Class loading",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 6, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_classes_loaded{kubernetes_pod_name=~\"$pod_name\"}",
     "legendFormat": "loaded [{$pod_name}]"
    }
   ]
  },
  {
   "title": "Threads used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_current{kubernetes_pod_name=~\"$pod_name\"}",
     "legendFormat": "current [{$pod_name}]"
    },
    {
     "expr": "jvm_threads_daemon{kubernetes_pod_name=~\"$pod_name\"}",
     "legendFormat": "daemon [{$pod_name}]"
    },
    {
     "expr": "jvm_threads_peak{kubernetes_pod_name=~\"$pod_name\"}",
     "legendFormat": "peak [{$pod_name}]"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "java_lang_OperatingSystem_ProcessCpuTime{kubernetes_pod_name=~\"$pod_name\"}",
     "legendFormat": "ProcessCpuTime[{$pod_name}]"
    },
    {
     "expr": "java_lang_OperatingSystem_SystemLoadAverage{kubernetes_pod_name=~\"$pod_name\"}",
     "legendFormat": "SystemCpuAvg[{$pod_name}]"
    },
    {
     "expr": "sum(rate(node_cpu_seconds_total[1m])) by (mode) * 100 / count(node_cpu_seconds_total) by (mode) or sum(irate(node_cpu_seconds_total[5m])) by (mode) * 100 / count(node_cpu_seconds_total) by (mode)",
     "legendFormat": "{{ mode }}"
    }
   ]
  }
 ]
}