{
 "title": "Mulesoft JVM Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "pod_name",
    "label": "pod_name",
    "query": "label_values(kubernetes_pod_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "java_lang_OperatingSystem_ProcessCpuLoad{kubernetes_pod_name=~\"$pod_name\"}",
     "legendFormat": "ProcessCpuLoad[{$pod_name}]"
    },
    {
     "expr": "java_lang_OperatingSystem_SystemCpuLoad{kubernetes_pod_name=~\"$pod_name\"}",
     "legendFormat": "SystemCpuLoad[{$pod_name}]"
    }
   ]
  },
  {
   "title": "JVM Memory Pools(Heap)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "java_lang_MemoryPool_Usage_used{kubernetes_pod_name=~\"$pod_name\", name=~\"PS Eden Space|PS Old Gen|PS Survivor Space\"}",
     "legendFormat": "{{name}} [$pod_name]"
    }
   ]
  },
  {
   "title": "JVM Native Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "java_nio_BufferPool_TotalCapacity{kubernetes_pod_name=~\"$pod_name\"}",
     "legendFormat": "{{name}}  [$pod_name]"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "java_lang_OperatingSystem_ProcessCpuTime{kubernetes_pod_name=~\"$pod_name\"}",
     "legendFormat": "ProcessCpuTime[$pod_name]"
    },
    {
     "expr": "java_lang_OperatingSystem_SystemLoadAverage{kubernetes_pod_name=~\"$pod_name\"}",
     "legendFormat": "SystemCpuAvg[$pod_name]"
    }
   ]
  },
  {
   "title": "GC count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_gc_collection_seconds_count{kubernetes_pod_name=~\"$pod_name\"}",
     "legendFormat": "{{gc}} [{{kubernetes_pod_name}}]"
    },
    {
     "expr": "jvm_gc_collection_seconds_count{kubernetes_pod_name=~\"$pod_name\"}",
     "legendFormat": "{{gc}} [{{kubernetes_pod_name}}]"
    }
   ]
  },
  {
   "title": "Class loading",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_classes_loaded{kubernetes_pod_name=~\"$pod_name\"}",
     "legendFormat": "loaded [{$pod_name}]"
    }
   ]
  },
  {
   "title": "JVM Memory Pools(Non-Heap)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "java_lang_MemoryPool_Usage_used{kubernetes_pod_name=~\"$pod_name\", name=~\"Metaspace|Code Cache|Compressed Class Space\"}",
     "legendFormat": "{{name}} [$pod_name]"
    }
   ]
  },
  {
   "title": "Threads used",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_current{kubernetes_pod_name=~\"$pod_name\"}",
     "legendFormat": "current [{$pod_name}]"
    },
    {
     "expr": "jvm_threads_daemon{kubernetes_pod_name=~\"$pod_name\"}",
     "legendFormat": "daemon [{$pod_name}]"
    },
    {
     "expr": "jvm_threads_peak{kubernetes_pod_name=~\"$pod_name\"}",
     "legendFormat": "peak [{$pod_name}]"
    }
   ]
  },
  {
   "title": "GC time / 1 min. rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 14, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum{kubernetes_pod_name=~\"$pod_name\"}[1m])",
     "legendFormat": "{{gc}} [$pod_name]"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "java_lang_OperatingSystem_MaxFileDescriptorCount{kubernetes_pod_name=~\"$pod_name\"}",
     "legendFormat": "MaxFileDescriptorCount[{$pod_name}]"
    },
    {
     "expr": "java_lang_OperatingSystem_OpenFileDescriptorCount{kubernetes_pod_name=~\"$pod_name\"}",
     "legendFormat": "OpenFileDescriptorCount[{$pod_name}]"
    }
   ]
  }
 ]
}